name: Test Sprites

on:
  push:
    branch: 
      - main
  
  pull_request:
    branch:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

    test:
      needs: build
      runs-on: ubuntu-latest